### ISSUE TITLE
Linum-mode?

### ISSUE THREAD

**Issue by xmathe** [liuyinz/binky-mode#6]
Is there any conflict between binky-margin-mode and linum-mode?
While linum-mode is enabled binky margin symbols are not displayed.

**Comment by eki3z** [comment]
Linum-mode use the margin, so it confilcts with binky-mode indeed. Maybe you should use `display-line-numbers-mode` (since 26.0.50) instead. In the future, I would implement the fringe indicator support, that would solve the confilcts with
`linum-mode`.

<img width="731" alt="Screen Shot 2022-12-22 at 23 37 46" src="https://user-images.githubusercontent.com/35212403/209170015-09ec68e4-86a3-4a65-ba4b-d21cd08d5b34.png">
